$(document).ready(function(){
  $("#play1").click(function(){
    $(".hide1").fadeIn();
    $(".clause1").fadeIn();
  });
  $("#play2").click(function(){
    $(".hide2").fadeIn();
    $(".clause2").fadeIn();
  });
